const defaultConfig = {
  theme: 'classic',
  general: {
    formType: 'popup',
    title: 'Veuillez remplir le formulaire pour commander',
    // Empty means "use the country selected for the store". This avoids
    // pinning every new COD form to Cameroon before the store is configured.
    countries: [],
    popularCities: {
      Cameroon: ['Douala', 'Yaoundé', 'Bafoussam', 'Bamenda', 'Garoua', 'Maroua', 'Ngaoundéré', 'Bertoua', 'Kribi', 'Limbé'],
      'Côte d\'Ivoire': ['Abidjan', 'Bouaké', 'Yamoussoukro', 'San-Pédro', 'Daloa', 'Korhogo', 'Man', 'Divo', 'Gagnoa', 'Abengourou'],
      Sénégal: ['Dakar', 'Thiès', 'Saint-Louis', 'Ziguinchor', 'Kaolack', 'Mbour', 'Rufisque', 'Tambacounda', 'Richard-Toll', 'Louga'],
      Gabon: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda', 'Lambaréné', 'Mouila', 'Tchibanga'],
      Congo: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Owando', 'Ouesso', 'Impfondo'],
      RDC: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani', 'Goma', 'Bukavu', 'Tshikapa', 'Kolwezi'],
      Mali: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Ségou', 'Kayes', 'Gao', 'Kati'],
      Guinée: ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Labé', 'Mamou', 'Boké', 'Siguiri'],
      Togo: ['Lomé', 'Kara', 'Sokodé', 'Atakpamé', 'Kpalimé', 'Dapaong', 'Tsévié'],
      Bénin: ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey-Calavi', 'Djougou', 'Bohicon', 'Natitingou'],
      Burkina: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Ouahigouya', 'Banfora', 'Dédougou', 'Kaya'],
      Niger: ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez', 'Dosso', 'Diffa'],
      Tchad: ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kélo', 'Koumra'],
      Mauritanie: ['Nouakchott', 'Nouadhibou', 'Rosso', 'Kaédi', 'Zouérat', 'Kiffa'],
    },
    sections: [
      { id: 'heroSlogan',        label: 'Slogan marketing IA',       enabled: true  },
      { id: 'heroBaseline',      label: 'Phrase de réassurance IA',   enabled: true  },
      { id: 'reviews',           label: 'Avis clients',              enabled: true  },
      { id: 'orderForm',         label: '🛒 Bouton / Formulaire',    enabled: true  },
      { id: 'productGallery',    label: 'Photos du produit',         enabled: true  },
      { id: 'statsBar',          label: 'Barre de stats sociales',   enabled: false },
      { id: 'stockCounter',      label: 'Compteur de stock',         enabled: false },
      { id: 'urgencyBadge',      label: 'Badge d\'urgence',          enabled: true  },
      { id: 'urgencyElements',   label: 'Éléments d\'urgence',       enabled: true  },
      { id: 'benefitsBullets',   label: 'Bénéfices produit',         enabled: true  },
      { id: 'comparison',        label: 'Tableau comparatif',        enabled: true  },
      { id: 'conversionBlocks',  label: 'Blocs de réassurance',      enabled: true  },
      { id: 'offerBlock',        label: 'Bloc garantie / offre',     enabled: true  },
      { id: 'description',       label: 'Description produit',       enabled: true  },
      { id: 'problemSection',    label: 'Section Problème',          enabled: true  },
      { id: 'solutionSection',   label: 'Section Solution',          enabled: true  },
      { id: 'faq',               label: 'Section FAQ',               enabled: true  },
      { id: 'testimonials',      label: 'Témoignages clients',       enabled: true  },
      { id: 'relatedProducts',   label: 'Produits similaires',       enabled: true  },
      { id: 'stickyOrderBar',    label: 'Barre de commande fixe',    enabled: true  },
      { id: 'upsell',            label: 'Upsell',                    enabled: true  },
      { id: 'orderBump',         label: 'Order Bump',                enabled: true  },
    ],
  },
  conversion: {
    quantities: [1, 2, 3],
    offersEnabled: false,
    offers: [
      { qty: 1, price: 0, comparePrice: 0, badge: '', selected: true },
      { qty: 2, price: 0, comparePrice: 0, badge: 'Le plus populaire 🔥', selected: false },
      { qty: 3, price: 0, comparePrice: 0, badge: 'Meilleure offre 💰', selected: false },
    ],
  },
  automation: {
    whatsapp: {
      enabled: false,
      number: '',
      message: 'Bonjour {{name}}, votre commande {{product}} est confirmée.',
    },
  },
  callSchedule: {
    enabled: true,
    question: 'À quel moment vouliez-vous qu\'on vous appelle ?',
    options: [
      { label: '08h30 – 10h30', value: '08h30-10h30' },
      { label: '12h00 – 14h00', value: '12h00-14h00' },
      { label: '16h00 – 18h00', value: '16h00-18h00' },
      { label: 'Flexible', value: 'flexible' },
    ],
  },
  urgency: {
    enabled: true,
    text: 'Plus tôt vous agissez sur le soin de votre corps, plus vite vous retrouvez votre confort. Le stock est presque épuisé et la promotion se termine dans',
    countdown: true,
    countdownMinutes: 15,
  },
  design: {
    buttonColor: '#D94A1F',
    buttonTextColor: '#ffffff',
    buttonFontSize: '16px',
    buttonBold: true,
    buttonItalic: false,
    buttonBorderColor: '#D94A1F',
    buttonBorderWidth: '0px',
    buttonShadow: '4',
    backgroundColor: '#ffffff',
    textColor: '#1F2937',
    fontSize: '16px',
    formBold: false,
    formItalic: false,
    labelAlign: 'left',
    ctaButtonColor: '',     // empty = inherit from buttonColor
    // Form-specific colors (set by FormThemePicker, editable via pickers)
    formBgColor: '#ffffff',
    formTextColor: '#111827',
    formButtonColor: '',    // empty = inherit from buttonColor / ctaButtonColor
    formBorderColor: '#E5E7EB',
    formBorderWidth: '1px',
    formBorderRadius: '12px',
    formInputRadius: '12px',
    formShadow: '0',
    fieldTextColor: '#111827',
    fieldBgColor: '#ffffff',
    fieldBorderColor: '#E5E7EB',
    fieldIconColor: '#9CA3AF',
    fieldIconBg: '#eCe7e7',
    badgeColor: '#EF4444',
    borderRadius: '8px',
    shadow: true,
    fontBase: 14,
    fontWeight: '600',
  },
  button: {
    text: 'ACHETER MAINTENANT',
    subtext: '',
    priceInButton: true,
    icon: 'cart',
    animation: 'none',
    // Visual params — fully independent from design tab
    bgColor: '',        // empty = inherits design.buttonColor
    textColor: '#ffffff',
    fontSize: 16,
    bold: true,
    italic: false,
    borderColor: '',
    borderWidth: 0,
    borderRadius: 14,
    shadow: 4,
  },
  form: {
    formTheme: 'classic',
    fields: [
      { name: 'product_info',    label: 'Contenu du panier / Offres de quantité',        type: 'product_info', enabled: true,  editable: false },
      { name: 'fullname',        label: 'Nom complet',                                   type: 'text',         enabled: true,  required: true,  icon: 'user',  showLabel: true, showIcon: true, placeholder: 'Nom complet' },
      { name: 'phone',           label: 'Numéro de téléphone',                           type: 'phone',        enabled: true,  required: true,  icon: 'phone', showLabel: true, showIcon: true, placeholder: 'Numéro de téléphone' },
      { name: 'city',            label: 'Ville',                                         type: 'city_select',  enabled: true,  required: true,  icon: 'map',   showLabel: true, showIcon: true, placeholder: 'Ville', cityAuto: true },
      { name: 'address',         label: 'Lieu de livraison',                             type: 'text',         enabled: true,  required: true,  icon: 'pin',   showLabel: true, showIcon: true, placeholder: 'Lieu de livraison' },
      { name: 'shipping_options', label: 'Les options d\'expédition',                     type: 'shipping',     enabled: true,  editable: false },
      { name: 'cta_button',      label: 'ACHETER MAINTENANT - {total}',                  type: 'cta_button',   enabled: true,  editable: true,
        icon: 'cart', showIcon: true, showLabel: true, placeholder: 'Texte du bouton',
        animation: 'none',
        bgColor: '',        // empty = inherits design.ctaButtonColor / design.buttonColor
        textColor: '#ffffff',
        fontSize: 15,
        bold: true,
        italic: false,
        borderColor: '',
        borderWidth: 0,
        borderRadius: 14,
        shadow: 4,
      },
    ],
  },
  // Custom testimonials — overrides product._pageData.testimonials and defaults when set
  testimonials: [],
};

export default defaultConfig;
