export const PAYMENT_COUNTRY_CODES = [
  { code: '+237', flag: '🇨🇲', country: 'Cameroun' },
  { code: '+221', flag: '🇸🇳', country: 'Sénégal' },
  { code: '+225', flag: '🇨🇮', country: "Côte d'Ivoire" },
  { code: '+223', flag: '🇲🇱', country: 'Mali' },
  { code: '+226', flag: '🇧🇫', country: 'Burkina Faso' },
  { code: '+229', flag: '🇧🇯', country: 'Bénin' },
  { code: '+228', flag: '🇹🇬', country: 'Togo' },
  { code: '+227', flag: '🇳🇪', country: 'Niger' },
  { code: '+224', flag: '🇬🇳', country: 'Guinée' },
  { code: '+234', flag: '🇳🇬', country: 'Nigeria' },
  { code: '+233', flag: '🇬🇭', country: 'Ghana' },
  { code: '+231', flag: '🇱🇷', country: 'Liberia' },
  { code: '+33', flag: '🇫🇷', country: 'France' },
  { code: '+32', flag: '🇧🇪', country: 'Belgique' },
  { code: '+41', flag: '🇨🇭', country: 'Suisse' },
  { code: '+1', flag: '🇨🇦', country: 'Canada' },
  { code: '+1', flag: '🇺🇸', country: 'États-Unis' },
];